# Example labeler.yml configuration

# Add 'root' label to any changes in root files
root:
  - changed-files:
      - any-glob-to-any-file: '*'

# Add 'GlobalChange' label to any changes within the entire repository
GlobalChange:
  - changed-files:
      - any-glob-to-any-file: '**'

# Add 'Documentation' label to any changes within 'docs' folder or any subfolders
Documentation:
  - changed-files:
      - any-glob-to-any-file: 'src/docs/**'
      - any-glob-to-any-file: '**/*.md'

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
  - all:
      - changed-files:
          - any-glob-to-any-file: 'src/**/*'
          - all-globs-to-all-files: '!src/docs/**'
          - all-globs-to-all-files: '!src/components/**'

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
  - any:
      - head-branch: ['^feature', 'feature']

# Add 'release' label to any PR that is opened against the `main` branch
release:
  - base-branch: 'main'
